services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  app:
    environment:
      DB_ENGINE: postgres
    build:
      args:
        DB_ENGINE: postgres

volumes:
  pgdata: